
language: java
jdk: oraclejdk8


install: true

sudo: required
before_script:
  - sudo apt-get update
  - sudo apt-get install lib32z1 lib32ncurses5
  
after_success:
  - mvn site
  - bash <(curl -s https://codecov.io/bash)
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
