
language: java
jdk: oraclejdk8


install: true

sudo: required
before_script:
  - sudo apt-get update
  - sudo apt-get install lib32z1 lib32ncurses5
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
