
language: java
jdk: openjdk8
install: true
sudo: required
addons:
  sonarcloud:
    organization: "4hwc-4hwc-autonomous-car"
    token:
      secure: $SONAR_TOKEN_4HWC_AUTONOMOUS_CAR
before_script:
  - sudo apt-get update
  - sudo apt-get install lib32z1 lib32ncurses5
  
after_success:
  - mvn site
  - bash <(curl -s https://codecov.io/bash)
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
  
