coverage:
  ignore:
    - "src/main/java/com/autonomouscar/model/"
    - "src/main/java/com/autonomouscar/utils/"
    - "src/main/java/com/autonomouscar/logs/"
    - "src/main/java/com/autonomouscar/exceptions/"
